### ISSUE TITLE
from_file(path="/netlists/lut_1.v", name="LUT_WINPUT1") fails on lexer

### ISSUE THREAD

**Issue by roy-pstr** [circuitgraph/circuitgraph#26]
Just to make sure it is intended, the lexer format does not support in input vector? such as 'input [0:10] x;'?

Example:

command in python console: 
c=cg.from_file(r'lut1.v','LUT_WINPUT1')

following error:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\lark\lexer.py", line 466, in lex
    token = self.root_lexer.next_token(lexer_state, parser_state)
  File "C:\Program Files\Python37\lib\site-packages\lark\lexer.py", line 380, in next_token
    state=parser_state, terminals_by_name=self.terminals_by_name)
lark.exceptions.UnexpectedCharacters: No terminal matches '[' in the current parser context, at line 2 col 9

  input [0:0] in;
        ^
Expected one of:
        * "1'h0"
        * "1'b0"
        * TILDE
        * BANG
        * COLON
        * IDENTIFIER
        * RPAR
        * VBAR
        * QMARK
        * CIRCUMFLEX
        * LPAR
        * "1'h1"
        * "1'b1"
        * DOT
        * "~^"
        * "^~"
        * SEMICOLON
        * AMPERSAND
        * EQUAL
        * COMMA

Previous tokens: Token('INPUT', 'input')

**Comment by jpsety** [comment]
These LUTs were left from a previous iteration of the code with bus support. It was removed because of some bugs/complexity. Ideally that functionality will be restored at some point. 

If you need a LUT, I'd suggest using a mux: ```cg.mux(2)```
